### ISSUE TITLE
Missing file in `srv`

### ISSUE THREAD

**Issue by xEnVrE** [mcsix/xela_server_ros2#1]
Dear all,

it seems that the `CMakeLists.txt` is searching for a file that does not exist in the current folder:

https://github.com/mcsix/xela_server_ros2/blob/e68a54503d1cad3ee1783f5126106b667e25f404/CMakeLists.txt#L28

Is this a leftover or do we actually need that to make the software run?

Thank you

**Comment by mcsix** [comment]
It is a residue from the old package.
Thank you for pointing it out.
I have removed that line from it now.

**Comment by xEnVrE** [comment]
Thanks a lot!
